/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // Drevet av CSS-variabler fra theme.ts/styles.css — lar oss bytte
        // mørk/lys uten å forandre klasser.
        bg: "rgb(var(--c-bg) / <alpha-value>)",
        surface: "rgb(var(--c-surface) / <alpha-value>)",
        elevated: "rgb(var(--c-elevated) / <alpha-value>)",
        pressed: "rgb(var(--c-pressed) / <alpha-value>)",
        border: "rgb(var(--c-border) / <alpha-value>)",
        divider: "rgb(var(--c-divider) / <alpha-value>)",
        text: "rgb(var(--c-text) / <alpha-value>)",
        muted: "rgb(var(--c-muted) / <alpha-value>)",
        subtle: "rgb(var(--c-subtle) / <alpha-value>)",
        inverse: "rgb(var(--c-inverse) / <alpha-value>)",
        primary: "rgb(var(--c-primary) / <alpha-value>)",
        "primary-hover": "rgb(var(--c-primary-hover) / <alpha-value>)",
        "primary-soft": "rgb(var(--c-primary-soft) / <alpha-value>)",
        accent: "rgb(var(--c-accent) / <alpha-value>)",
        "accent-soft": "rgb(var(--c-accent-soft) / <alpha-value>)",
        success: "rgb(var(--c-success) / <alpha-value>)",
        "success-soft": "rgb(var(--c-success-soft) / <alpha-value>)",
        warning: "rgb(var(--c-warning) / <alpha-value>)",
        "warning-soft": "rgb(var(--c-warning-soft) / <alpha-value>)",
        danger: "rgb(var(--c-danger) / <alpha-value>)",
        "danger-soft": "rgb(var(--c-danger-soft) / <alpha-value>)",
        info: "rgb(var(--c-info) / <alpha-value>)",
        "info-soft": "rgb(var(--c-info-soft) / <alpha-value>)",
        reseptA: "rgb(var(--c-reseptA) / <alpha-value>)",
        "reseptA-soft": "rgb(var(--c-reseptA-soft) / <alpha-value>)",
        reseptB: "rgb(var(--c-reseptB) / <alpha-value>)",
        "reseptB-soft": "rgb(var(--c-reseptB-soft) / <alpha-value>)",
        reseptC: "rgb(var(--c-reseptC) / <alpha-value>)",
        "reseptC-soft": "rgb(var(--c-reseptC-soft) / <alpha-value>)",
        ventral: "rgb(var(--c-ventral) / <alpha-value>)",
      },
      fontFamily: {
        sans: [
          "InterVariable",
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "Segoe UI",
          "Roboto",
          "sans-serif",
        ],
        mono: [
          "JetBrains Mono",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "monospace",
        ],
      },
      fontSize: {
        // Aldersvennlig minimum 14 px, basisleder 16 px
        "captionSmall": ["12px", { lineHeight: "16px" }],
        "caption": ["13px", { lineHeight: "18px" }],
        "label": ["13px", { lineHeight: "16px", letterSpacing: "0.02em" }],
        "body": ["15px", { lineHeight: "22px" }],
        "bodyMedium": ["15px", { lineHeight: "22px", fontWeight: "500" }],
        "bodySemibold": ["15px", { lineHeight: "22px", fontWeight: "600" }],
        "button": ["15px", { lineHeight: "20px", fontWeight: "600" }],
        "buttonSmall": ["13px", { lineHeight: "16px", fontWeight: "600" }],
        "h3": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "h2": ["22px", { lineHeight: "28px", fontWeight: "700" }],
        "h1": ["28px", { lineHeight: "34px", fontWeight: "700" }],
        "hero": ["40px", { lineHeight: "46px", fontWeight: "800" }],
      },
      borderRadius: {
        xs: "4px",
        sm: "6px",
        md: "10px",
        lg: "14px",
        xl: "20px",
        xxl: "28px",
      },
      boxShadow: {
        sm: "0 1px 2px rgb(15 23 42 / 0.06)",
        md: "0 4px 12px rgb(15 23 42 / 0.08)",
        lg: "0 12px 32px rgb(15 23 42 / 0.12)",
        xl: "0 24px 48px rgb(15 23 42 / 0.18)",
        glow: "0 0 0 4px rgb(var(--c-primary) / 0.12)",
      },
      animation: {
        "fade-in": "fadeIn 0.18s ease-out both",
        "slide-up": "slideUp 0.22s cubic-bezier(0.2,0.8,0.2,1) both",
        "slide-down": "slideDown 0.22s cubic-bezier(0.2,0.8,0.2,1) both",
        shimmer: "shimmer 1.5s linear infinite",
        "pulse-soft": "pulseSoft 2.4s ease-in-out infinite",
      },
      keyframes: {
        fadeIn: { from: { opacity: "0" }, to: { opacity: "1" } },
        slideUp: {
          from: { transform: "translateY(12px)", opacity: "0" },
          to: { transform: "translateY(0)", opacity: "1" },
        },
        slideDown: {
          from: { transform: "translateY(-12px)", opacity: "0" },
          to: { transform: "translateY(0)", opacity: "1" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        pulseSoft: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.55" },
        },
      },
    },
  },
  plugins: [],
};
